export ZSH=/Users/waybetter/.oh-my-zsh
export EDITOR=vim

ZSH_THEME="robbyrussell"

plugins=(brew aws gitfast gem ssh-agent common-aliases docker gem git git-flow-avh tmuxinator yarn)

alias be='bundle exec'
alias ls='ls -FG'
alias l='ls -l'
alias la='ls -la'
alias c='clear'
alias vi='vim'
alias ctags="`brew --prefix`/bin/ctags"
alias webstart='kmd start -- local ${PWD##*/} -m convox.local.yml'
alias webrun='convox run web --rack local/convox'
alias webssh='kmd ko -- l ${PWD##*/} web'
# alias in-billing-service-do='wbin-gen2 wb-billing-service bundle exec '
# alias in-notify-service-do='wbin-gen2 wb-notify-service bundle exec '

alias sz='source ~/.zshrc'

export PATH="$HOME/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:$HOME/code/waybetter/kraken/bin:$HOME/go/bin"

source $ZSH/oh-my-zsh.sh

zstyle :omz:plugins:ssh-agent agent-forwarding on

if [ -d ~/.zsh ]; then
  for i in ~/.zsh/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

#source /usr/local/share/chruby/chruby.sh
#source /usr/local/share/chruby/auto.sh

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# autocompletion
fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i
