export ZSH=/home/frank/.oh-my-zsh
export EDITOR=vim

ZSH_THEME="robbyrussell"

plugins=(gitfast gem ssh-agent common-aliases gem git tmuxinator yarn)

alias be='bundle exec'
alias ls='ls -FG'
alias l='ls -l'
alias la='ls -la'
alias c='clear'
alias sz='source ~/.zshrc'
alias vim="nvim"
alias vi="nvim"

export PATH="$HOME/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

source $ZSH/oh-my-zsh.sh

zstyle :omz:plugins:ssh-agent agent-forwarding on

# bindkey -e; bindkey '\e\e[C' forward-word; bindkey '\e\e[D' backward-word
bindkey "5C" forward-word
bindkey "5D" backward-word

if [ -d ~/.zsh ]; then
  for i in ~/.zsh/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

[ -f /usr/share/autojump/autojump.sh ] && . /usr/share/autojump/autojump.sh

# autocompletion
fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i
export PATH="/usr/local/sbin:$HOME/.cargo/bin:$PATH"
. /home/frank/.asdf/asdf.sh
. /home/frank/.asdf/completions/asdf.bash
